name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Add a workflow_dispatch trigger to allow manual runs (e.g., for 'destroy')
  workflow_dispatch: 

jobs:
  # ====================================================================
  # BUILD, VALIDATE, & PLAN JOB
  # This job runs automatically on push/PR.
  # ====================================================================
  terraform_plan:
    runs-on: ubuntu-latest
    
    # Define environment variables once for the job
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Ensure you configure your backend state file, usually via TF config
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5 # Current version is good!

      # ----------------------------------------------------------------
      # NEW: Terraform Format Check
      # Checks if all files are correctly formatted. This is a best practice.
      # ----------------------------------------------------------------
      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        # Only run plan on Pull Requests
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        env:
          TF_VAR_environment: staging # Use a staging variable for testing
          
      # ----------------------------------------------------------------
      # Existing Apply step is now conditional based on the plan job's success
      # ----------------------------------------------------------------
      - name: Terraform Apply
        id: apply
        # Only run apply on a push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_environment: production # Use a production variable for the main branch

 